.PHONY: help up down restart logs ps shell db-shell test test-v migrate migration rollback clean

.DEFAULT_GOAL := help

help: ## Show this help message
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# --- Containers ---
up: ## Start all services in the background
	docker compose up -d

down: ## Stop all services
	docker compose down

build: ## Rebuild container images
	docker compose build

restart: ## Restart API container
	docker compose restart api

logs: ## Tail API logs
	docker compose logs -f api

ps: ## List running services
	docker compose ps

# --- Shell Access ---
shell: ## Open an interactive bash shell inside the API container
	docker compose exec api bash

db-shell: ## Open PostgreSQL interactive shell (psql)
	docker compose exec db psql -U api_user -d api_database

# --- Testing ---
test: ## Run test suite inside container
	docker compose exec api pytest

test-v: ## Run test suite with verbose output
	docker compose exec api pytest -vv

# --- Database & Migrations ---
migrate: ## Apply database migrations
	docker compose exec api alembic upgrade head

migration: ## Create a new autogenerated migration (usage: make migration msg="add_table")
	docker compose exec api alembic revision --autogenerate -m "$(msg)"

rollback: ## Rollback last migration
	docker compose exec api alembic downgrade -1

# --- Cleanup ---
clean: ## Remove local cache and build artifacts
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type d -name ".pytest_cache" -exec rm -rf {} +
