from __future__ import annotations

from dataclasses import dataclass, field

from app.domain.value_objects import (
    DeviceId,
    MeasurementId,
    MeasurementType,
    MeasurementUnit,
    MeasurementValue,
    Timestamp,
)


@dataclass
class Measurement:
    """Domain entity representing a telemetry measurement generated by an IoT device."""

    device_id: DeviceId
    type: MeasurementType
    value: MeasurementValue
    unit: MeasurementUnit
    id: MeasurementId = field(default_factory=MeasurementId)
    timestamp: Timestamp = field(default_factory=Timestamp)
