"""add_device_is_active_and_fk_constraints

Revision ID: 9023476ba729
Revises: 8b117ec1b50d
Create Date: 2026-09-24 18:51:45.457657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9023476ba729'
down_revision: Union[str, Sequence[str], None] = '8b117ec1b50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_foreign_key(None, 'devices', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'measurements', 'devices', ['device_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'is_active')
    # ### end Alembic commands ###
